<?php

namespace AppBundle\Repository;

/**
 * IndentDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndentDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
