<?php

namespace AppBundle\Repository;

/**
 * ObjectTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
