<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends EntityRepository
{
    public function findPetsByKindParent($id = null){

        $rsm = new ResultSetMapping();

        if($id === null){
            $query = $this->getEntityManager()->createNativeQuery('
            CREATE TEMPORARY TABLE cte AS (
                    SELECT pet.id, pet.parent_id
                    FROM   pet
                    WHERE  pet.parent_id IS NULL
                    
                    UNION  ALL
            
                    SELECT e.id, e.parent_id
                    FROM   cte c
                    JOIN   pet e ON e.id = c.parent_id
             );
            SELECT * FROM cte;', $rsm);
        } else {
            $query = $this->getEntityManager()->createNativeQuery('
            CREATE TEMPORARY TABLE cte AS (
                    SELECT pet.id, pet.parent_id
                    FROM   pet
                    WHERE  pet.parent_id = ?
                    
                    UNION  ALL
            
                    SELECT e.id, e.parent_id
                    FROM   cte c
                    JOIN   pet e ON e.id = c.parent_id
             );
            SELECT * FROM cte;', $rsm);

            $query->setParameter(1, $id);
        }
        return $query->getResult();
    }

    public function findFirstKindOfPet(){

        $rsm = new ResultSetMapping();

        $query = $this->getEntityManager()->createNativeQuery('
            SELECT * FROM pet WHERE pet.parent_id IS NULL', $rsm);

        return $query->getResult();

    }
}
