<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends EntityRepository
{
    public function findPetsByKind(){
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('AppBundle:Pet', 'pet');
        $rsm->addFieldResult('pet', 'id', 'id');
        $rsm->addFieldResult('pet', 'parent', 'parent');

        $query = $this->getEntityManager()->createNativeQuery('
            with recursive cte as (
                    SELECT pet.id, pet.parent
                    FROM   pet
            
                    UNION  ALL
            
                    SELECT e.id, e.parent
                    FROM   cte c
                    JOIN   group e ON e.id = c.parent
             )
            SELECT * FROM cte;', $rsm);

        return $query->getResult();
    }

    public function findFirstKindOfPet(){

        $rsm = new ResultSetMapping();

        $query = $this->getEntityManager()->createNativeQuery('
            SELECT pet.label FROM pet WHERE pet.parent = NULL', $rsm);

        return $query->getResult();

    }
}
