app:
    resource: '@AppBundle/Controller/'
    type: annotation

create_user:
    path: /create/user
    defaults: {_controller: AppBundle:User:add}

create_pannier:
    path: /create/panier
    defaults: {_controller: AppBundle:Indent:createIndent}
